all:
	../../../../bin/go-bindata \
		-pkg assets \
		-o "assets.go" \
		-nomemcopy \
		-nocompress \
		-prefix "../../../../" \
		../../../../final/images/ \
		../../../../final/sounds/ \
		../../../../final